//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.1433
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ulif
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.0.0.2968")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_Ilib5", Namespace="http://tempuri.org/")]
    public partial class dictlib : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        
        /// <remarks/>
        public dictlib()
        {
            this.Url = "http://193.125.79.234:38005/ulif/service/lib5";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/IDataPageRetriever/SupplyPageOfData", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ListElement[] SupplyPageOfData(int lowerPageBoundary, int rowsPerPage, dic dicFlag, bool singledict)
        {
            object[] results = this.Invoke("SupplyPageOfData", new object[] {
                        lowerPageBoundary,
                        rowsPerPage,
                        dicFlag,
                        singledict});
            return ((ListElement[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSupplyPageOfData(int lowerPageBoundary, int rowsPerPage, dic dicFlag, bool singledict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SupplyPageOfData", new object[] {
                        lowerPageBoundary,
                        rowsPerPage,
                        dicFlag,
                        singledict}, callback, asyncState);
        }
        
        /// <remarks/>
        public ListElement[] EndSupplyPageOfData(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListElement[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/ReestrGetID", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReestrGetID(int i, dic dict, bool singledict)
        {
            object[] results = this.Invoke("ReestrGetID", new object[] {
                        i,
                        dict,
                        singledict});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReestrGetID(int i, dic dict, bool singledict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ReestrGetID", new object[] {
                        i,
                        dict,
                        singledict}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndReestrGetID(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/ReestrGetLen", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReestrGetLen(dic dict)
        {
            object[] results = this.Invoke("ReestrGetLen", new object[] {
                        dict});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReestrGetLen(dic dict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ReestrGetLen", new object[] {
                        dict}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndReestrGetLen(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/ReestrGetWord", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReestrGetWord(int id)
        {
            object[] results = this.Invoke("ReestrGetWord", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReestrGetWord(int id, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ReestrGetWord", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndReestrGetWord(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerateWPar(string word, int id, string fstyle, dic dtype)
        {
            object[] results = this.Invoke("GenerateWPar", new object[] {
                        word,
                        id,
                        fstyle,
                        dtype});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerateWPar(string word, int id, string fstyle, dic dtype, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GenerateWPar", new object[] {
                        word,
                        id,
                        fstyle,
                        dtype}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndGenerateWPar(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar2", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateWPar2(string word, int id, string fstyle, dic dtype)
        {
            object[] results = this.Invoke("GenerateWPar2", new object[] {
                        word,
                        id,
                        fstyle,
                        dtype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerateWPar2(string word, int id, string fstyle, dic dtype, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GenerateWPar2", new object[] {
                        word,
                        id,
                        fstyle,
                        dtype}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGenerateWPar2(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar3", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateWPar3(string word, int id, string fstyle, dic dtype)
        {
            object[] results = this.Invoke("GenerateWPar3", new object[] {
                        word,
                        id,
                        fstyle,
                        dtype});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerateWPar3(string word, int id, string fstyle, dic dtype, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GenerateWPar3", new object[] {
                        word,
                        id,
                        fstyle,
                        dtype}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGenerateWPar3(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/SearchWord", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SearchWord(string w, dic dict, bool singledict, out bool r)
        {
            object[] results = this.Invoke("SearchWord", new object[] {
                        w,
                        dict,
                        singledict});
            r = ((bool)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchWord(string w, dic dict, bool singledict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SearchWord", new object[] {
                        w,
                        dict,
                        singledict}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSearchWord(System.IAsyncResult asyncResult, out bool r)
        {
            object[] results = this.EndInvoke(asyncResult);
            r = ((bool)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/SearchDicWord", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SearchDicWord(string w, dic d, bool singledict, out bool r)
        {
            object[] results = this.Invoke("SearchDicWord", new object[] {
                        w,
                        d,
                        singledict});
            r = ((bool)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchDicWord(string w, dic d, bool singledict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SearchDicWord", new object[] {
                        w,
                        d,
                        singledict}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSearchDicWord(System.IAsyncResult asyncResult, out bool r)
        {
            object[] results = this.EndInvoke(asyncResult);
            r = ((bool)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/SearchOrderNum", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SearchOrderNum(int id, dic dict, bool singledict, out bool res)
        {
            object[] results = this.Invoke("SearchOrderNum", new object[] {
                        id,
                        dict,
                        singledict});
            res = ((bool)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchOrderNum(int id, dic dict, bool singledict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SearchOrderNum", new object[] {
                        id,
                        dict,
                        singledict}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSearchOrderNum(System.IAsyncResult asyncResult, out bool res)
        {
            object[] results = this.EndInvoke(asyncResult);
            res = ((bool)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/existdict", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool existdict(int uid, dic d)
        {
            object[] results = this.Invoke("existdict", new object[] {
                        uid,
                        d});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexistdict(int uid, dic d, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("existdict", new object[] {
                        uid,
                        d}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endexistdict(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/existdicts", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("s")]
        public bool existdicts(int uid, out bool f, out bool a)
        {
            object[] results = this.Invoke("existdicts", new object[] {
                        uid});
            f = ((bool)(results[1]));
            a = ((bool)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexistdicts(int uid, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("existdicts", new object[] {
                        uid}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endexistdicts(System.IAsyncResult asyncResult, out bool f, out bool a)
        {
            object[] results = this.EndInvoke(asyncResult);
            f = ((bool)(results[1]));
            a = ((bool)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/DictPrepare", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DictPrepare(int uid, string art, string fstyle, dic d, bool singledict)
        {
            object[] results = this.Invoke("DictPrepare", new object[] {
                        uid,
                        art,
                        fstyle,
                        d,
                        singledict});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDictPrepare(int uid, string art, string fstyle, dic d, bool singledict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DictPrepare", new object[] {
                        uid,
                        art,
                        fstyle,
                        d,
                        singledict}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndDictPrepare(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/DictPrepare2", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DictPrepare2(int uid, string art, string fstyle, dic d, bool singledict)
        {
            object[] results = this.Invoke("DictPrepare2", new object[] {
                        uid,
                        art,
                        fstyle,
                        d,
                        singledict});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDictPrepare2(int uid, string art, string fstyle, dic d, bool singledict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DictPrepare2", new object[] {
                        uid,
                        art,
                        fstyle,
                        d,
                        singledict}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDictPrepare2(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/phrasPrepare", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] phrasPrepare(int uid, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] out phraseology[] phras)
        {
            object[] results = this.Invoke("phrasPrepare", new object[] {
                        uid});
            phras = ((phraseology[])(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginphrasPrepare(int uid, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("phrasPrepare", new object[] {
                        uid}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndphrasPrepare(System.IAsyncResult asyncResult, out phraseology[] phras)
        {
            object[] results = this.EndInvoke(asyncResult);
            phras = ((phraseology[])(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getpharticle", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getpharticle(int aid, sbyte l, string fstyle, bool singledict)
        {
            object[] results = this.Invoke("getpharticle", new object[] {
                        aid,
                        l,
                        fstyle,
                        singledict});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetpharticle(int aid, sbyte l, string fstyle, bool singledict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getpharticle", new object[] {
                        aid,
                        l,
                        fstyle,
                        singledict}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetpharticle(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getpharticle2", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getpharticle2(int aid, sbyte l, string fstyle, bool singledict)
        {
            object[] results = this.Invoke("getpharticle2", new object[] {
                        aid,
                        l,
                        fstyle,
                        singledict});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetpharticle2(int aid, sbyte l, string fstyle, bool singledict, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getpharticle2", new object[] {
                        aid,
                        l,
                        fstyle,
                        singledict}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetpharticle2(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/phcmp", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int phcmp(string word1, string word2)
        {
            object[] results = this.Invoke("phcmp", new object[] {
                        word1,
                        word2});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginphcmp(string word1, string word2, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("phcmp", new object[] {
                        word1,
                        word2}, callback, asyncState);
        }
        
        /// <remarks/>
        public int Endphcmp(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/GetAppName", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAppName()
        {
            object[] results = this.Invoke("GetAppName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAppName(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAppName", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAppName(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/checkver", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool checkver(string sver, out string[] a)
        {
            object[] results = this.Invoke("checkver", new object[] {
                        sver});
            a = ((string[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincheckver(string sver, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("checkver", new object[] {
                        sver}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool Endcheckver(System.IAsyncResult asyncResult, out string[] a)
        {
            object[] results = this.EndInvoke(asyncResult);
            a = ((string[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/processmorph", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public morphstr[] processmorph(string text)
        {
            object[] results = this.Invoke("processmorph", new object[] {
                        text});
            return ((morphstr[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginprocessmorph(string text, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("processmorph", new object[] {
                        text}, callback, asyncState);
        }
        
        /// <remarks/>
        public morphstr[] Endprocessmorph(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((morphstr[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getcwf", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getcwf(string w)
        {
            object[] results = this.Invoke("getcwf", new object[] {
                        w});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetcwf(string w, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getcwf", new object[] {
                        w}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetcwf(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/processaccent", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string processaccent(string text)
        {
            object[] results = this.Invoke("processaccent", new object[] {
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginprocessaccent(string text, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("processaccent", new object[] {
                        text}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endprocessaccent(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/processtranscr", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string processtranscr(string text)
        {
            object[] results = this.Invoke("processtranscr", new object[] {
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginprocesstranscr(string text, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("processtranscr", new object[] {
                        text}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endprocesstranscr(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getAllPart", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool getAllPart(string inputWord, [System.Xml.Serialization.XmlArrayAttribute()] out byte[] res)
        {
            object[] results = this.Invoke("getAllPart", new object[] {
                        inputWord});
            res = ((byte[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllPart(string inputWord, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getAllPart", new object[] {
                        inputWord}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndgetAllPart(System.IAsyncResult asyncResult, out byte[] res)
        {
            object[] results = this.EndInvoke(asyncResult);
            res = ((byte[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getAllFirstWFormsWithParts", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WordUniAndPartAndOmon[] getAllFirstWFormsWithParts(string inputWord)
        {
            object[] results = this.Invoke("getAllFirstWFormsWithParts", new object[] {
                        inputWord});
            return ((WordUniAndPartAndOmon[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllFirstWFormsWithParts(string inputWord, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getAllFirstWFormsWithParts", new object[] {
                        inputWord}, callback, asyncState);
        }
        
        /// <remarks/>
        public WordUniAndPartAndOmon[] EndgetAllFirstWFormsWithParts(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WordUniAndPartAndOmon[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getsemcomm", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getsemcomm(int uni, out string f6, out string f7)
        {
            object[] results = this.Invoke("getsemcomm", new object[] {
                        uni});
            f6 = ((string)(results[1]));
            f7 = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetsemcomm(int uni, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getsemcomm", new object[] {
                        uni}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetsemcomm(System.IAsyncResult asyncResult, out string f6, out string f7)
        {
            object[] results = this.EndInvoke(asyncResult);
            f6 = ((string)(results[1]));
            f7 = ((string)(results[2]));
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.0.0.2968")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ulif.org.ua/services/lib5")]
    public enum dic
    {
        
        /// <remarks/>
        INFL_DIC,
        
        /// <remarks/>
        TRANSCR_DIC,
        
        /// <remarks/>
        PHRAS_DIC,
        
        /// <remarks/>
        SYN_DIC,
        
        /// <remarks/>
        ANT_DIC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.0.0.2968")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ulif.org.ua/services/lib5")]
    public partial class ListElement
    {
        
        /// <remarks/>
        public int uid;
        
        /// <remarks/>
        public string w;
        
        /// <remarks/>
        public bool s;
        
        /// <remarks/>
        public bool f;
        
        /// <remarks/>
        public bool a;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.0.0.2968")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ulif.org.ua/services/lib5")]
    public partial class WordUniAndPartAndOmon
    {
        
        /// <remarks/>
        public int uni;
        
        /// <remarks/>
        public string forma;
        
        /// <remarks/>
        public string part;
        
        /// <remarks/>
        public byte part_id;
        
        /// <remarks/>
        public byte omon;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.0.0.2968")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ulif.org.ua/services/lib5")]
    public partial class morphstr
    {
        
        /// <remarks/>
        public string word;
        
        /// <remarks/>
        public string scode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.0.0.2968")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ulif.org.ua/services/lib5")]
    public partial class phraseology
    {
        
        /// <remarks/>
        public int id;
        
        /// <remarks/>
        public string phras;
        
        /// <remarks/>
        public sbyte l;
        
        /// <remarks/>
        public int aid;
        
        /// <remarks/>
        public int sort;
    }
}
