//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace ulif {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_Ilib5", Namespace="http://tempuri.org/")]
    public partial class dictlib : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public dictlib() {
            this.Url = "http://lcorp.ulif.org.ua/ILib5/Service.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/IDataPageRetriever/SupplyPageOfData", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ulif.org.ua/lib5/", IsNullable=false)]
        public ListElement[] SupplyPageOfData(int lowerPageBoundary, [System.Xml.Serialization.XmlIgnoreAttribute()] bool lowerPageBoundarySpecified, int rowsPerPage, [System.Xml.Serialization.XmlIgnoreAttribute()] bool rowsPerPageSpecified, gldescdic dicFlag, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dicFlagSpecified, bool singledict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool singledictSpecified) {
            object[] results = this.Invoke("SupplyPageOfData", new object[] {
                        lowerPageBoundary,
                        lowerPageBoundarySpecified,
                        rowsPerPage,
                        rowsPerPageSpecified,
                        dicFlag,
                        dicFlagSpecified,
                        singledict,
                        singledictSpecified});
            return ((ListElement[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSupplyPageOfData(int lowerPageBoundary, bool lowerPageBoundarySpecified, int rowsPerPage, bool rowsPerPageSpecified, gldescdic dicFlag, bool dicFlagSpecified, bool singledict, bool singledictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SupplyPageOfData", new object[] {
                        lowerPageBoundary,
                        lowerPageBoundarySpecified,
                        rowsPerPage,
                        rowsPerPageSpecified,
                        dicFlag,
                        dicFlagSpecified,
                        singledict,
                        singledictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public ListElement[] EndSupplyPageOfData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListElement[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/ReestrGetID", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReestrGetID(int i, [System.Xml.Serialization.XmlIgnoreAttribute()] bool iSpecified, gldescdic dict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dictSpecified, bool singledict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool singledictSpecified, out int ReestrGetIDResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ReestrGetIDResultSpecified) {
            object[] results = this.Invoke("ReestrGetID", new object[] {
                        i,
                        iSpecified,
                        dict,
                        dictSpecified,
                        singledict,
                        singledictSpecified});
            ReestrGetIDResult = ((int)(results[0]));
            ReestrGetIDResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReestrGetID(int i, bool iSpecified, gldescdic dict, bool dictSpecified, bool singledict, bool singledictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReestrGetID", new object[] {
                        i,
                        iSpecified,
                        dict,
                        dictSpecified,
                        singledict,
                        singledictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndReestrGetID(System.IAsyncResult asyncResult, out int ReestrGetIDResult, out bool ReestrGetIDResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ReestrGetIDResult = ((int)(results[0]));
            ReestrGetIDResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/ReestrGetLen", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReestrGetLen(gldescdic dict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dictSpecified, out int ReestrGetLenResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ReestrGetLenResultSpecified) {
            object[] results = this.Invoke("ReestrGetLen", new object[] {
                        dict,
                        dictSpecified});
            ReestrGetLenResult = ((int)(results[0]));
            ReestrGetLenResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReestrGetLen(gldescdic dict, bool dictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReestrGetLen", new object[] {
                        dict,
                        dictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndReestrGetLen(System.IAsyncResult asyncResult, out int ReestrGetLenResult, out bool ReestrGetLenResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ReestrGetLenResult = ((int)(results[0]));
            ReestrGetLenResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/ReestrGetWord", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReestrGetWord(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            object[] results = this.Invoke("ReestrGetWord", new object[] {
                        id,
                        idSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReestrGetWord(int id, bool idSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReestrGetWord", new object[] {
                        id,
                        idSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndReestrGetWord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] GenerateWPar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string word, int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fstyle, gldescdic dtype, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dtypeSpecified) {
            object[] results = this.Invoke("GenerateWPar", new object[] {
                        word,
                        id,
                        idSpecified,
                        fstyle,
                        dtype,
                        dtypeSpecified});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerateWPar(string word, int id, bool idSpecified, string fstyle, gldescdic dtype, bool dtypeSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GenerateWPar", new object[] {
                        word,
                        id,
                        idSpecified,
                        fstyle,
                        dtype,
                        dtypeSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndGenerateWPar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar2", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GenerateWPar2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string word, int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fstyle, gldescdic dtype, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dtypeSpecified) {
            object[] results = this.Invoke("GenerateWPar2", new object[] {
                        word,
                        id,
                        idSpecified,
                        fstyle,
                        dtype,
                        dtypeSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerateWPar2(string word, int id, bool idSpecified, string fstyle, gldescdic dtype, bool dtypeSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GenerateWPar2", new object[] {
                        word,
                        id,
                        idSpecified,
                        fstyle,
                        dtype,
                        dtypeSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGenerateWPar2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/GenerateWPar3", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GenerateWPar3([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string word, int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fstyle, gldescdic dtype, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dtypeSpecified) {
            object[] results = this.Invoke("GenerateWPar3", new object[] {
                        word,
                        id,
                        idSpecified,
                        fstyle,
                        dtype,
                        dtypeSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerateWPar3(string word, int id, bool idSpecified, string fstyle, gldescdic dtype, bool dtypeSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GenerateWPar3", new object[] {
                        word,
                        id,
                        idSpecified,
                        fstyle,
                        dtype,
                        dtypeSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGenerateWPar3(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/SearchWord", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SearchWord([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string w, gldescdic dict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dictSpecified, bool singledict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool singledictSpecified, out int SearchWordResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SearchWordResultSpecified, out bool r, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool rSpecified) {
            object[] results = this.Invoke("SearchWord", new object[] {
                        w,
                        dict,
                        dictSpecified,
                        singledict,
                        singledictSpecified});
            SearchWordResult = ((int)(results[0]));
            SearchWordResultSpecified = ((bool)(results[1]));
            r = ((bool)(results[2]));
            rSpecified = ((bool)(results[3]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchWord(string w, gldescdic dict, bool dictSpecified, bool singledict, bool singledictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchWord", new object[] {
                        w,
                        dict,
                        dictSpecified,
                        singledict,
                        singledictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSearchWord(System.IAsyncResult asyncResult, out int SearchWordResult, out bool SearchWordResultSpecified, out bool r, out bool rSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            SearchWordResult = ((int)(results[0]));
            SearchWordResultSpecified = ((bool)(results[1]));
            r = ((bool)(results[2]));
            rSpecified = ((bool)(results[3]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/SearchDicWord", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SearchDicWord([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string w, gldescdic d, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dSpecified, bool singledict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool singledictSpecified, out int SearchDicWordResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SearchDicWordResultSpecified, out bool r, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool rSpecified) {
            object[] results = this.Invoke("SearchDicWord", new object[] {
                        w,
                        d,
                        dSpecified,
                        singledict,
                        singledictSpecified});
            SearchDicWordResult = ((int)(results[0]));
            SearchDicWordResultSpecified = ((bool)(results[1]));
            r = ((bool)(results[2]));
            rSpecified = ((bool)(results[3]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchDicWord(string w, gldescdic d, bool dSpecified, bool singledict, bool singledictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchDicWord", new object[] {
                        w,
                        d,
                        dSpecified,
                        singledict,
                        singledictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSearchDicWord(System.IAsyncResult asyncResult, out int SearchDicWordResult, out bool SearchDicWordResultSpecified, out bool r, out bool rSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            SearchDicWordResult = ((int)(results[0]));
            SearchDicWordResultSpecified = ((bool)(results[1]));
            r = ((bool)(results[2]));
            rSpecified = ((bool)(results[3]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/SearchOrderNum", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SearchOrderNum(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified, gldescdic dict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dictSpecified, bool singledict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool singledictSpecified, out int SearchOrderNumResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SearchOrderNumResultSpecified, out bool res, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool resSpecified) {
            object[] results = this.Invoke("SearchOrderNum", new object[] {
                        id,
                        idSpecified,
                        dict,
                        dictSpecified,
                        singledict,
                        singledictSpecified});
            SearchOrderNumResult = ((int)(results[0]));
            SearchOrderNumResultSpecified = ((bool)(results[1]));
            res = ((bool)(results[2]));
            resSpecified = ((bool)(results[3]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearchOrderNum(int id, bool idSpecified, gldescdic dict, bool dictSpecified, bool singledict, bool singledictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SearchOrderNum", new object[] {
                        id,
                        idSpecified,
                        dict,
                        dictSpecified,
                        singledict,
                        singledictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSearchOrderNum(System.IAsyncResult asyncResult, out int SearchOrderNumResult, out bool SearchOrderNumResultSpecified, out bool res, out bool resSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            SearchOrderNumResult = ((int)(results[0]));
            SearchOrderNumResultSpecified = ((bool)(results[1]));
            res = ((bool)(results[2]));
            resSpecified = ((bool)(results[3]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/existdict", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void existdict(int uid, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uidSpecified, gldescdic d, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dSpecified, out bool existdictResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool existdictResultSpecified) {
            object[] results = this.Invoke("existdict", new object[] {
                        uid,
                        uidSpecified,
                        d,
                        dSpecified});
            existdictResult = ((bool)(results[0]));
            existdictResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexistdict(int uid, bool uidSpecified, gldescdic d, bool dSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("existdict", new object[] {
                        uid,
                        uidSpecified,
                        d,
                        dSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endexistdict(System.IAsyncResult asyncResult, out bool existdictResult, out bool existdictResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            existdictResult = ((bool)(results[0]));
            existdictResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/existdicts", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void existdicts(int uid, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uidSpecified, out bool s, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool sSpecified, out bool f, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool fSpecified, out bool a, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool aSpecified) {
            object[] results = this.Invoke("existdicts", new object[] {
                        uid,
                        uidSpecified});
            s = ((bool)(results[0]));
            sSpecified = ((bool)(results[1]));
            f = ((bool)(results[2]));
            fSpecified = ((bool)(results[3]));
            a = ((bool)(results[4]));
            aSpecified = ((bool)(results[5]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexistdicts(int uid, bool uidSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("existdicts", new object[] {
                        uid,
                        uidSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endexistdicts(System.IAsyncResult asyncResult, out bool s, out bool sSpecified, out bool f, out bool fSpecified, out bool a, out bool aSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            s = ((bool)(results[0]));
            sSpecified = ((bool)(results[1]));
            f = ((bool)(results[2]));
            fSpecified = ((bool)(results[3]));
            a = ((bool)(results[4]));
            aSpecified = ((bool)(results[5]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/DictPrepare", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] DictPrepare(int uid, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uidSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string art, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fstyle, gldescdic d, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dSpecified, bool singledict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool singledictSpecified) {
            object[] results = this.Invoke("DictPrepare", new object[] {
                        uid,
                        uidSpecified,
                        art,
                        fstyle,
                        d,
                        dSpecified,
                        singledict,
                        singledictSpecified});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDictPrepare(int uid, bool uidSpecified, string art, string fstyle, gldescdic d, bool dSpecified, bool singledict, bool singledictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DictPrepare", new object[] {
                        uid,
                        uidSpecified,
                        art,
                        fstyle,
                        d,
                        dSpecified,
                        singledict,
                        singledictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndDictPrepare(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/DictPrepare2", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DictPrepare2(int uid, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uidSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string art, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fstyle, gldescdic d, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dSpecified, bool singledict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool singledictSpecified) {
            object[] results = this.Invoke("DictPrepare2", new object[] {
                        uid,
                        uidSpecified,
                        art,
                        fstyle,
                        d,
                        dSpecified,
                        singledict,
                        singledictSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDictPrepare2(int uid, bool uidSpecified, string art, string fstyle, gldescdic d, bool dSpecified, bool singledict, bool singledictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DictPrepare2", new object[] {
                        uid,
                        uidSpecified,
                        art,
                        fstyle,
                        d,
                        dSpecified,
                        singledict,
                        singledictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDictPrepare2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/phrasPrepare", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] phrasPrepare(int uid, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uidSpecified, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/fdict", IsNullable=false)] out phrasdictphraseology[] phras) {
            object[] results = this.Invoke("phrasPrepare", new object[] {
                        uid,
                        uidSpecified});
            phras = ((phrasdictphraseology[])(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginphrasPrepare(int uid, bool uidSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("phrasPrepare", new object[] {
                        uid,
                        uidSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndphrasPrepare(System.IAsyncResult asyncResult, out phrasdictphraseology[] phras) {
            object[] results = this.EndInvoke(asyncResult);
            phras = ((phrasdictphraseology[])(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getpharticle", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getpharticle(int aid, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aidSpecified, sbyte l, [System.Xml.Serialization.XmlIgnoreAttribute()] bool lSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fstyle, bool singledict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool singledictSpecified) {
            object[] results = this.Invoke("getpharticle", new object[] {
                        aid,
                        aidSpecified,
                        l,
                        lSpecified,
                        fstyle,
                        singledict,
                        singledictSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetpharticle(int aid, bool aidSpecified, sbyte l, bool lSpecified, string fstyle, bool singledict, bool singledictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getpharticle", new object[] {
                        aid,
                        aidSpecified,
                        l,
                        lSpecified,
                        fstyle,
                        singledict,
                        singledictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetpharticle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getpharticle2", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getpharticle2(int aid, [System.Xml.Serialization.XmlIgnoreAttribute()] bool aidSpecified, sbyte l, [System.Xml.Serialization.XmlIgnoreAttribute()] bool lSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fstyle, bool singledict, [System.Xml.Serialization.XmlIgnoreAttribute()] bool singledictSpecified) {
            object[] results = this.Invoke("getpharticle2", new object[] {
                        aid,
                        aidSpecified,
                        l,
                        lSpecified,
                        fstyle,
                        singledict,
                        singledictSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetpharticle2(int aid, bool aidSpecified, sbyte l, bool lSpecified, string fstyle, bool singledict, bool singledictSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getpharticle2", new object[] {
                        aid,
                        aidSpecified,
                        l,
                        lSpecified,
                        fstyle,
                        singledict,
                        singledictSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetpharticle2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/phcmp", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void phcmp([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string word1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string word2, out int phcmpResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool phcmpResultSpecified) {
            object[] results = this.Invoke("phcmp", new object[] {
                        word1,
                        word2});
            phcmpResult = ((int)(results[0]));
            phcmpResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginphcmp(string word1, string word2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("phcmp", new object[] {
                        word1,
                        word2}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endphcmp(System.IAsyncResult asyncResult, out int phcmpResult, out bool phcmpResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            phcmpResult = ((int)(results[0]));
            phcmpResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/GetAppName", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetAppName() {
            object[] results = this.Invoke("GetAppName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAppName(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAppName", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetAppName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/checkver", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void checkver([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sver, out bool checkverResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool checkverResultSpecified, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] out string[] a) {
            object[] results = this.Invoke("checkver", new object[] {
                        sver});
            checkverResult = ((bool)(results[0]));
            checkverResultSpecified = ((bool)(results[1]));
            a = ((string[])(results[2]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begincheckver(string sver, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("checkver", new object[] {
                        sver}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endcheckver(System.IAsyncResult asyncResult, out bool checkverResult, out bool checkverResultSpecified, out string[] a) {
            object[] results = this.EndInvoke(asyncResult);
            checkverResult = ((bool)(results[0]));
            checkverResultSpecified = ((bool)(results[1]));
            a = ((string[])(results[2]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/processmorph", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ulif.org.ua/lib5/", IsNullable=false)]
        public morphstr[] processmorph([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string text) {
            object[] results = this.Invoke("processmorph", new object[] {
                        text});
            return ((morphstr[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginprocessmorph(string text, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("processmorph", new object[] {
                        text}, callback, asyncState);
        }
        
        /// <remarks/>
        public morphstr[] Endprocessmorph(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((morphstr[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getcwf", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getcwf([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string w) {
            object[] results = this.Invoke("getcwf", new object[] {
                        w});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetcwf(string w, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getcwf", new object[] {
                        w}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetcwf(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/processaccent", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string processaccent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string text) {
            object[] results = this.Invoke("processaccent", new object[] {
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginprocessaccent(string text, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("processaccent", new object[] {
                        text}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endprocessaccent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/processtranscr", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string processtranscr([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string text) {
            object[] results = this.Invoke("processtranscr", new object[] {
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginprocesstranscr(string text, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("processtranscr", new object[] {
                        text}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endprocesstranscr(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getAllPart", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getAllPart([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string inputWord, out bool getAllPartResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool getAllPartResultSpecified, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)] out byte[] res) {
            object[] results = this.Invoke("getAllPart", new object[] {
                        inputWord});
            getAllPartResult = ((bool)(results[0]));
            getAllPartResultSpecified = ((bool)(results[1]));
            res = ((byte[])(results[2]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllPart(string inputWord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllPart", new object[] {
                        inputWord}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndgetAllPart(System.IAsyncResult asyncResult, out bool getAllPartResult, out bool getAllPartResultSpecified, out byte[] res) {
            object[] results = this.EndInvoke(asyncResult);
            getAllPartResult = ((bool)(results[0]));
            getAllPartResultSpecified = ((bool)(results[1]));
            res = ((byte[])(results[2]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getAllFirstWFormsWithParts", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ulif.org.ua/lib5/", IsNullable=false)]
        public WordUniAndPartAndOmon[] getAllFirstWFormsWithParts([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string inputWord) {
            object[] results = this.Invoke("getAllFirstWFormsWithParts", new object[] {
                        inputWord});
            return ((WordUniAndPartAndOmon[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllFirstWFormsWithParts(string inputWord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllFirstWFormsWithParts", new object[] {
                        inputWord}, callback, asyncState);
        }
        
        /// <remarks/>
        public WordUniAndPartAndOmon[] EndgetAllFirstWFormsWithParts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WordUniAndPartAndOmon[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ulif.org.ua/services/lib5/Ilib5/getsemcomm", RequestNamespace="http://ulif.org.ua/services/lib5", ResponseNamespace="http://ulif.org.ua/services/lib5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string getsemcomm(int uni, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uniSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string f6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string f7) {
            object[] results = this.Invoke("getsemcomm", new object[] {
                        uni,
                        uniSpecified});
            f6 = ((string)(results[1]));
            f7 = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetsemcomm(int uni, bool uniSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getsemcomm", new object[] {
                        uni,
                        uniSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgetsemcomm(System.IAsyncResult asyncResult, out string f6, out string f7) {
            object[] results = this.EndInvoke(asyncResult);
            f6 = ((string)(results[1]));
            f7 = ((string)(results[2]));
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="gldesc.dic", Namespace="http://schemas.datacontract.org/2004/07/gldescript")]
    public enum gldescdic {
        
        /// <remarks/>
        INFL_DIC,
        
        /// <remarks/>
        TRANSCR_DIC,
        
        /// <remarks/>
        PHRAS_DIC,
        
        /// <remarks/>
        SYN_DIC,
        
        /// <remarks/>
        ANT_DIC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ulif.org.ua/lib5/")]
    public partial class ListElement {
        
        /// <remarks/>
        public bool a;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aSpecified;
        
        /// <remarks/>
        public bool f;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fSpecified;
        
        /// <remarks/>
        public bool s;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sSpecified;
        
        /// <remarks/>
        public int uid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uidSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string w;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ulif.org.ua/lib5/")]
    public partial class WordUniAndPartAndOmon {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string forma;
        
        /// <remarks/>
        public byte omon;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool omonSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string part;
        
        /// <remarks/>
        public byte part_id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool part_idSpecified;
        
        /// <remarks/>
        public int uni;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uniSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ulif.org.ua/lib5/")]
    public partial class morphstr {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string scode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string word;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="phrasdict.phraseology", Namespace="http://schemas.datacontract.org/2004/07/fdict")]
    public partial class phrasdictphraseology {
        
        /// <remarks/>
        public int aid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aidSpecified;
        
        /// <remarks/>
        public int id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified;
        
        /// <remarks/>
        public sbyte l;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string phras;
        
        /// <remarks/>
        public int sort;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sortSpecified;
    }
}
