#region License block : MPL 1.1/GPL 2.0/LGPL 2.1
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is the FreeCL.Net library.
 *
 * The Initial Developer of the Original Code is 
 *  Oleksii Prudkyi (Oleksii.Prudkyi@gmail.com).
 * Portions created by the Initial Developer are Copyright (C) 2008
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Translate
{
/*
Total count : 347, ignored : 253, unsupported 0
Code automatically generated by EnumDictd tool at 25.01.2009 4:55:28

Errors : 
dict://mova.org/ : Unable to connect to the dictionary server. : Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 208.70.148.81:2628
Connected : 
dict://dict.tugraz.at/ : 00.1093750
dict://dict.tu-chemnitz.de/ : 00.1562500
dict://nihongobenkyo.org/ : 00.1562500
dict://dictd.xdsl.by/ : 00.1875000
dict://la-sorciere.de/ : 00.1875000
dict://dict.bober757.org.ru/ : 00.2031250
dict://linicks.net/ : 00.2812500
dict://dictionary.bishopston.net/ : 00.3125000
dict://alt0.dict.org/ : 00.3125000
dict://dict.saugus.net/ : 00.3125000
dict://dict1.us.dict.org/ : 00.3750000
dict://dict.org/ : 00.4375000
dict://dict.arabeyes.org/ : 00.4531250
dict://dict.dvo.ru/ : 00.5625000
Databases : 
Ignored : afr-deu : Africaan-German Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : afr-eng : afr-eng : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : all : All Dictionaries (English-Only and Translating) : dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : compbe : English-Belarusian Computer Dictionary : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, 
Ignored : cze-eng : Czech-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : dan-eng : Danish-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : debian.bg-en : Българско - английски речник на Дебиан : dict://la-sorciere.de/, 
Ignored : debian.de-en : Debian Wörterbuch Deutsch-Englisch : dict://la-sorciere.de/, 
Ignored : debian.en-bg : Английско - български речник на Дебиан : dict://la-sorciere.de/, 
Ignored : debian.en-de : Debian Wörterbuch Englisch-Deutsch : dict://la-sorciere.de/, 
Ignored : debian.en-es : Diccionario Inglés-Español de Debian : dict://la-sorciere.de/, 
Ignored : debian.en-fi : Dictionary Englsh - Finnish : dict://la-sorciere.de/, 
Ignored : debian.en-fr "Petit lexique anglais-français de termes et abbréviations  : Debian : dict://la-sorciere.de/, 
Ignored : debian.en-lt : Dictionary en - lt : dict://la-sorciere.de/, 
Ignored : debian.en-nl : Debian Dictionaire English-Nederlands : dict://la-sorciere.de/, 
Ignored : debian.en-pa : Debian Dictionary English-Punjabi : dict://la-sorciere.de/, 
Ignored : debian.en-pl : Debian Słownik angielsko-polski : dict://la-sorciere.de/, 
Ignored : debian.en-pt : Dicionário Debian Inglês-Português : dict://la-sorciere.de/, 
Ignored : debian.en-vi : Từ điển Anh-Việt : dict://la-sorciere.de/, 
Ignored : debian.es-en : Diccionario Español-Inglés de Debian : dict://la-sorciere.de/, 
Ignored : debian.fi-en : Dictionary Finnish - English : dict://la-sorciere.de/, 
Ignored : debian.fr-en "Petit lexique français-anglais de termes et abbréviations  : Debian : dict://la-sorciere.de/, 
Ignored : debian.lt-en : Dictionary lt - en : dict://la-sorciere.de/, 
Ignored : debian.nl-en : Debian Dictionaire Nederlands-English : dict://la-sorciere.de/, 
Ignored : debian.pa-en : Debian Dictionary Punjabi-English : dict://la-sorciere.de/, 
Ignored : debian.pl-en : Debian Słownik polsko-angielski : dict://la-sorciere.de/, 
Ignored : debian.pt-en : Dicionário Debian Português-Inglês : dict://la-sorciere.de/, 
Ignored : debian.vi-en : Từ điển Việt-Anh : dict://la-sorciere.de/, 
Ignored : debian-glossary.bg : Речник на Debian и списък на съкращенията : dict://la-sorciere.de/, 
Ignored : debian-glossary.de : Debian Wörterbuch und Abkürzungsverzeichnis : dict://la-sorciere.de/, 
Ignored : debian-glossary.en : Debian Dictionary and List of Acronyms : dict://la-sorciere.de/, 
Ignored : debian-glossary.es : Diccionario y lista de acrónimos de Debian : dict://la-sorciere.de/, 
Ignored : debian-glossary.fi : Debian Dictionary and List of Acronyms : dict://la-sorciere.de/, 
Ignored : debian-glossary.fr "Petit lexique de termes et d'abbréviations : Debian : dict://la-sorciere.de/, 
Ignored : debian-glossary.lt : Debian'o žodynas ir akronimų sąrašas : dict://la-sorciere.de/, 
Ignored : debian-glossary.nl : Debian Dictionary and List of Acronyms : dict://la-sorciere.de/, 
Ignored : debian-glossary.pa : ਡੈਬੀਅਨ ਸ਼ਬਦ-ਕੋਸ਼ ਤੇ Acronyms ਸੂਚੀ : dict://la-sorciere.de/, 
Ignored : debian-glossary.pl : Słownik : dict://la-sorciere.de/, 
Ignored : debian-glossary.pt : Dicionário Debian e Lista de Acrônimos : dict://la-sorciere.de/, 
Ignored : debian-glossary.vi : Từ điển và Danh sách Từ cấu tạo Debian : dict://la-sorciere.de/, 
Ignored : debian-l10n.de-en : Dictionary de - en : dict://la-sorciere.de/, 
Ignored : debian-l10n.en-de : Dictionary en - de : dict://la-sorciere.de/, 
Ignored : debian-l10n-glossary.de : Glossary : dict://la-sorciere.de/, 
Ignored : debian-l10n-glossary.en : Glossary : dict://la-sorciere.de/, 
Ignored : debian-l10n-main.de : Acronyms : dict://la-sorciere.de/, 
Ignored : debian-l10n-main.en : Acronyms : dict://la-sorciere.de/, 
Ignored : de-ru : A collection of German-Russian dictionaries : dict://dictd.xdsl.by/, 
Ignored : deu-fra : German-French Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : deu-ita : German-Italian Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : deu-por : German-Portugese Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : devil : The Devil's Dictionary (1881-1906) : dict://dict.tugraz.at/, dict://la-sorciere.de/, 
Ignored : dward.bg : Справочен файл със съкращенията за жените в Debian : dict://la-sorciere.de/, 
Ignored : dward.de : Debian Abkürzungs-Referenz-Wörterterbuch : dict://la-sorciere.de/, 
Ignored : dward.en : Debian Acronym Reference Dictionary : dict://la-sorciere.de/, 
Ignored : dward.es : Debian Acronym Reference Dictionary : dict://la-sorciere.de/, 
Ignored : dward.fi : Debian Acronym Reference Dictionary : dict://la-sorciere.de/, 
Ignored : dward.fr "Petit lexique de termes et d'abbréviations : Debian : dict://la-sorciere.de/, 
Ignored : dward.lt : Debian'o Moterų akronimų nuorodų žodynas : dict://la-sorciere.de/, 
Ignored : dward.nl : Debian Acronym Reference Dictionary : dict://la-sorciere.de/, 
Ignored : dward.pa : Debian Acronym Reference Dictionary : dict://la-sorciere.de/, 
Ignored : dward.pl : Akronimy : dict://la-sorciere.de/, 
Ignored : dward.pt : Dicionário de Referência de Acrônimos : dict://la-sorciere.de/, 
Ignored : dward.vi : Từ điển Tham chiếu Từ cấu tạo Phụ nữ Debian : dict://la-sorciere.de/, 
Ignored : en-en--ru-ru : Подборка - толковые словари английского, русского языка (Webster, WordNet, FOLDOC, Ожегов, Ожегов-Шведова) : dict://dict.dvo.ru/, 
Ignored : eng-afr : eng-afr : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-fra : eng-fra : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-iri : English-Irish Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-ita : English-Italian Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-lat : English-Latin Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : english : English Monolingual Dictionaries : dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : english-german : English - German Dictionary 1.3 : dict://dict.tugraz.at/, 
Ignored : english-welsh : English-Welsh Freedict dictionary : dict://dictionary.bishopston.net/, 
Ignored : eng-nld : English-Netherlands Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-rom : English-Romanian FreeDict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-rus : English-Russian Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-spa : English-Spanish Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-swa : English-Swahili xFried/FreeDict Dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-swe : English-Swedish Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : eng-wel : English-Welsh Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : en-ru : A collection of English-Russian dictionaries : dict://dictd.xdsl.by/, 
Ignored : et-ru : A collection of Estonian-Russian dictionaries : dict://dictd.xdsl.by/, 
Ignored : --exit-- : Stop default search here. : dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : fd-afr-deu : Africaan-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-cze-eng : Czech-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-dan-eng : Danish-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-deu-eng : German-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-deu-fra : German-French Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-deu-ita : German-Italian Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-deu-nld : German-Nederland Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-deu-por : German-Portugese Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-deu : English-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-fra : English-French Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-hun : English-Hungarian Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-iri : English-Irish Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-ita : English-Italian Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-lat : English-Latin Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-nld : English-Netherlands Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-por : English-Portugese Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-rus : English-Russian Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-spa : English-Spanish Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-swe : English-Swedish Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-eng-wel : English-Welsh Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-fra-deu : French-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-fra-eng : French-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-fra-nld : French-Nederlands Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-hun-eng : fd-hun-eng : dict://dict.tugraz.at/, 
Ignored : fd-iri-eng : Irish-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-ita-deu : Italian-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-jpn-deu : Japanese-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-lat-deu : Latin-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-lat-eng : Latin-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-nld-deu : Nederlands-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-nld-eng : Nederlands-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-nld-fra : Nederlands-French Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-por-deu : Portugese-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-por-eng : Portugese-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-sco-deu : Scottish-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-scr-eng : fd-scr-eng : dict://dict.tugraz.at/, 
Ignored : fd-slo-eng : Slovenian-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-spa-eng : Spanish-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-swa-eng : Swahili-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-swe-eng : Swedish-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-tur-deu : Turkish-German Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fd-tur-eng : Turkish-English Freedict dictionary : dict://dict.tugraz.at/, 
Ignored : fi-ru : A collection of Finnish-Russian dictionaries : dict://dictd.xdsl.by/, 
Ignored : fra-deu : French-German Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : fra-eng : French-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : fra-nld : French-Nederlands Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : freedict-afr-deu : Afrikaans-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-cro-eng : Croatian-English Freedict Dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-cze-eng : Czech-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-dan-eng : Danish-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-deu-eng : German-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-deu-fra : German-French Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-deu-ita : German-Italian Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-deu-nld : German-Dutch Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-deu-por : German-Portuguese Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-ara : English-Arabic FreeDict Dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-cro : English-Croatian Freedict Dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-cze : English-Czech fdicts/FreeDict Dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-deu : English-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-fra : English-French Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-hin : English-Hindi Freedict Dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-hun : unknown : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-iri : English-Irish Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-ita : English-Italian Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-lat : English-Latin Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-nld : English-Dutch Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-por : English-Portuguese Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-rom : English-Romanian FreeDict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-rus : English-Russian Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-scr : English-Serbo-Croat Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-spa : English-Spanish Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-swa : English-Swahili xFried/FreeDict Dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-swe : English-Swedish Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-tur : English-Turkish FreeDict Dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-eng-wel : English-Welsh Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-fra-deu : French-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-fra-eng : French-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-fra-nld : French-Dutch Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-gla-deu : Scottish Gaelic-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-hin-eng : English-Hindi Freedict Dictionary [reverse index] : dict://dict.bober757.org.ru/, 
Ignored : freedict-hun-eng : unknown : dict://dict.bober757.org.ru/, 
Ignored : freedict-iri-eng : Irish-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-ita-deu : Italian-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-ita-eng : Italian-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-jpn-deu : Japanese-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-lat-deu : Latin-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-lat-eng : Latin-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-nld-deu : Dutch-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-nld-eng : Dutch-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-nld-fra : Dutch-French Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-por-deu : Portuguese-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-por-eng : Portuguese-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-sco-deu : Scottish-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-scr-eng : Serbo-Croat-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-slo-eng : Slovak-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-spa-eng : Spanish-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-swa-eng : Swahili-English xFried/FreeDict Dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-swe-eng : Swedish-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-tur-deu : Turkish-German Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : freedict-tur-eng : English-Turkish FreeDict Dictionary [reverse index] : dict://dict.bober757.org.ru/, 
Ignored : freedict-wel-eng : Welsh-English Freedict dictionary : dict://dict.bober757.org.ru/, 
Ignored : gaz : U.S. Gazetteer (1990) : dict://dict.tugraz.at/, dict://la-sorciere.de/, 
Ignored : gaz2k-counties : U.S. Gazetteer Counties (2000) : dict://dict.tugraz.at/, 
Ignored : gaz2k-places : U.S. Gazetteer Places (2000) : dict://dict.tugraz.at/, 
Ignored : gaz2k-zips : U.S. Gazetteer Zip Code Tabulation Areas (2000) : dict://dict.tugraz.at/, 
Ignored : gazetteer2k-counties : U.S. Gazetteer Counties (2000) : dict://dictionary.bishopston.net/, 
Ignored : gazetteer2k-places : U.S. Gazetteer Places (2000) : dict://dictionary.bishopston.net/, 
Ignored : gazetteer2k-zips : U.S. Gazetteer Zip Code Tabulation Areas (2000) : dict://dictionary.bishopston.net/, 
Ignored : german-english : German - English Dictionary 1.3 : dict://dict.tugraz.at/, 
Ignored : iri-eng : Irish-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : ita-deu : Italian-German Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : jpn-deu : Japanese-German Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : kha-deu : Khasi-German FreeDict Dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : komi-rus : Komi-Russian Dictionary : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, 
Ignored : lat-deu : Latin-German Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, dict://dict.dvo.ru/, 
Ignored : lat-eng : Latin-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, dict://dict.dvo.ru/, 
Ignored : mech : mech : dict://dictd.xdsl.by/, 
Ignored : mech_mime : mech : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, 
Ignored : moby-thesaurus : Moby Thesaurus II by Grady Ward, 1.0 : dict://dict.tugraz.at/, dict://dictionary.bishopston.net/, 
Ignored : mueller7 : Mueller English-Russian Dictionary : dict://dictd.xdsl.by/, 
Ignored : mueller-abbrev : List of abbreviations : dict://dict.dvo.ru/, 
Ignored : mueller-base : Base dictionary : dict://dict.dvo.ru/, 
Ignored : mueller-dict : Introduction : dict://dict.dvo.ru/, 
Ignored : mueller-geo : List of place-names : dict://dict.dvo.ru/, 
Ignored : mueller-names : List of personal names : dict://dict.dvo.ru/, 
Ignored : por-deu : Portugese-German Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : ru-de : A collection of Russian-German dictionaries : dict://dictd.xdsl.by/, 
Ignored : ru-en : A collection of Russian-English dictionaries : dict://dictd.xdsl.by/, 
Ignored : ru-en--en-ru : Подборка - агло-русские, русско-английские словари (Мюллер, Королев, Синягин, ... ) : dict://dict.dvo.ru/, 
Ignored : ru-ru : A collection of Russian monolingual dictionaries : dict://dictd.xdsl.by/, 
Ignored : ru-uk : A collection of Russian-Ukraine dictionaries : dict://dictd.xdsl.by/, 
Ignored : sco-deu : Scottish-German Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : scr-eng : Serbo-Croat-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : slo-eng : Slovenian-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : slovniks : Подборка - словники ru-blr, ru-en, ru-pl, ru-ukr, blr-en, blr-pl, blr-ru, ... : dict://dict.dvo.ru/, 
Ignored : slovnyk_be-en : slovnyk_be-en : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_be-pl : slovnyk_be-pl : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_be-ru : slovnyk_be-ru : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_be-uk : slovnyk_be-uk : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_en-be : slovnyk_en-be : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_en-pl : slovnyk_en-pl : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_en-ru : slovnyk_en-ru : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_en-uk : slovnyk_en-uk : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_pl-be : slovnyk_pl-be : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_pl-en : slovnyk_pl-en : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_pl-ru : slovnyk_pl-ru : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_pl-uk : slovnyk_pl-uk : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_ru-be : slovnyk_ru-be : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_ru-en : slovnyk_ru-en : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_ru-pl : slovnyk_ru-pl : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_ru-uk : slovnyk_ru-uk : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_uk-be : slovnyk_uk-be : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, dict://dict.dvo.ru/, 
Ignored : slovnyk_uk-en : slovnyk_uk-en : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, 
Ignored : slovnyk_uk-pl : slovnyk_uk-pl : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, 
Ignored : slovnyk_uk-ru : slovnyk_uk-ru : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, 
Ignored : SN-Sa : Saugus Related Terms, 2008-08-25 (Copyright 1998-2008 Saugus.net) : dict://dict.saugus.net/, 
Ignored : spa-eng : Spanish-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : swa-eng : Swahili-English xFried/FreeDict Dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : swe-eng : Swedish-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : tanaka_corpus_subset : Tanaka Corpus Subset : dict://nihongobenkyo.org/, 
Ignored : trans : Translating Dictionaries : dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : tur-deu : Turkish-German Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : tur-eng : Turkish-English Freedict dictionary : dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, 
Ignored : uk-ru : A collection of Ukraine-Russian dictionaries : dict://dictd.xdsl.by/, 
Ignored : web1913 : Webster's Revised Unabridged Dictionary (1913) : dict://dict.tu-chemnitz.de/, dict://dict.bober757.org.ru/, dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, dict://dict.dvo.ru/, 
Ignored : wel-eng : Welsh-English Freedict dictionary : dict://dictionary.bishopston.net/, 
Ignored : welsh-english : Welsh-English Freedict dictionary : dict://dictionary.bishopston.net/, 
Ignored : wn : WordNet (r) 2.0 (August 2003) : dict://dict.tugraz.at/, dict://dict.tu-chemnitz.de/, dict://la-sorciere.de/, dict://dict.bober757.org.ru/, dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, dict://dict.dvo.ru/, 
Ignored : world95 : The CIA World Factbook (1995) : dict://dict.tu-chemnitz.de/, dict://dict.bober757.org.ru/, dict://dictionary.bishopston.net/, dict://alt0.dict.org/, dict://dict1.us.dict.org/, dict://dict.org/, dict://dict.dvo.ru/, 
Ignored : zhelezyaki_abbr : USSR abbreviations for chips : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, 
Ignored : zhelezyaki_analogs : Analogs for USSR chips : dict://dictd.xdsl.by/, dict://dict.bober757.org.ru/, 
*/




public class Dictd1000pbioDictionary : DictDMonolingualDictionary
{
	public Dictd1000pbioDictionary()
	{
		Name = "1000pbio";
		Description = "1000+ brief biographical data";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.History);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdAbr1wDictionary : DictDSynonymsDictionary
{
	public DictdAbr1wDictionary()
	{
		Name = "abr1w";
		Description = "Dictionary of synonyms of N.Abramov";
		AddSupportedTranslation(Language.Russian, Language.Russian);
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);
		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdAhiezerDictionary : DictDMonolingualDictionary
{
	public DictdAhiezerDictionary()
	{
		Name = "ahiezer";
		Description = "Terms of book «Criticism of historical experience» of A. Akhiezer";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.History);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdArabicDictionary : DictDBilingualDictionary
{
	public DictdArabicDictionary()
	{
		Name = "arabic";
		Description = "Arabeyes English/Arabic dictionary";
		AddSupportedTranslation(Language.English, Language.Arabic);
		AddSupportedTranslation(Language.English_GB, Language.Arabic);
		AddSupportedTranslation(Language.English_US, Language.Arabic);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dict.arabeyes.org/"));
	}
}
public class DictdAraEngDictionary : DictDBilingualDictionary
{
	public DictdAraEngDictionary()
	{
		Name = "ara-eng";
		Description = "Arabic-English Freedict Dictionary";
		AddSupportedTranslation(Language.Arabic, Language.English);
		AddSupportedTranslation(Language.Arabic, Language.English_GB);
		AddSupportedTranslation(Language.Arabic, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdAviationDictionary : DictDMonolingualDictionary
{
	public DictdAviationDictionary()
	{
		Name = "aviation";
		Description = "Russian abbreviations for aviation";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Aviation);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdBeslovDictionary : DictDMonolingualDictionary
{
	public DictdBeslovDictionary()
	{
		Name = "beslov";
		Description = "Large Encyclopedic Dictionary";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdBiologyDictionary : DictDBilingualDictionary
{
	public DictdBiologyDictionary()
	{
		Name = "biology";
		Description = "Russian-English Dictionary of Biology";
		AddSupportedTranslation(Language.Russian, Language.English);
		AddSupportedTranslation(Language.Russian, Language.English_GB);
		AddSupportedTranslation(Language.Russian, Language.English_US);

		AddSupportedSubject(SubjectConstants.Biology);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdBouvierDictionary : DictDMonolingualDictionary
{
	public DictdBouvierDictionary()
	{
		Name = "bouvier";
		Description = "Bouvier's Law Dictionary, Revised 6th Ed (1856)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Law);

		Urls.Add(new Uri("dict://dict.tugraz.at/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdBrok_and_efrDictionary : DictDMonolingualDictionary
{
	public DictdBrok_and_efrDictionary()
	{
		Name = "brok_and_efr";
		Description = "Brockhaus and Efron's encyclopaedic dictionary";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdBusDictionary : DictDMonolingualDictionary
{
	public DictdBusDictionary()
	{
		Name = "bus";
		Description = "Big dictionary of law";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Law);

		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdChurchDictionary : DictDMonolingualDictionary
{
	public DictdChurchDictionary()
	{
		Name = "church";
		Description = "Dictionary of the church terms";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Bible);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdCroEngDictionary : DictDBilingualDictionary
{
	public DictdCroEngDictionary()
	{
		Name = "cro-eng";
		Description = "Croatian-English Freedict Dictionary";
		AddSupportedTranslation(Language.Croatian, Language.English);
		AddSupportedTranslation(Language.Croatian, Language.English_GB);
		AddSupportedTranslation(Language.Croatian, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdDalfDictionary : DictDMonolingualDictionary
{
	public DictdDalfDictionary()
	{
		Name = "dalf";
		Description = "Explanatory dictionary of live Russian language of V.I.Dalja";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdDeuEngDictionary : DictDBilingualDictionary
{
	public DictdDeuEngDictionary()
	{
		Name = "deu-eng";
		Description = "German-English Freedict dictionary";
		AddSupportedTranslation(Language.German, Language.English);
		AddSupportedTranslation(Language.German, Language.English_GB);
		AddSupportedTranslation(Language.German, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://la-sorciere.de/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdDeuNldDictionary : DictDBilingualDictionary
{
	public DictdDeuNldDictionary()
	{
		Name = "deu-nld";
		Description = "German-Nederland Freedict dictionary";
		AddSupportedTranslation(Language.Dutch, Language.English);
		AddSupportedTranslation(Language.Dutch, Language.English_GB);
		AddSupportedTranslation(Language.Dutch, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdDeutsch_deRuDictionary : DictDBilingualDictionary
{
	public DictdDeutsch_deRuDictionary()
	{
		Name = "deutsch_de-ru";
		Description = "Deutsch-Russian dictionary";
		AddSupportedTranslation(Language.German, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
	}
}
public class DictdDeutsch_ruDeDictionary : DictDBilingualDictionary
{
	public DictdDeutsch_ruDeDictionary()
	{
		Name = "deutsch_ru-de";
		Description = "Russian-Deutsch dictionary";
		AddSupportedTranslation(Language.Russian, Language.German);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdDevilsDictionary : DictDMonolingualDictionary
{
	public DictdDevilsDictionary()
	{
		Name = "devils";
		Description = "THE DEVIL'S DICTIONARY ((C)1911 Released April 15 1993)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Humour);

		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdEastonDictionary : DictDMonolingualDictionary
{
	public DictdEastonDictionary()
	{
		Name = "easton";
		Description = "Easton's 1897 Bible Dictionary";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Bible);

		Urls.Add(new Uri("dict://dict.tugraz.at/"));
		Urls.Add(new Uri("dict://dict.tu-chemnitz.de/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdEdictFrDictionary : DictDBilingualDictionary
{
	public DictdEdictFrDictionary()
	{
		Name = "edict-fr";
		Description = "Japanese to French dictionary";
		AddSupportedTranslation(Language.Japanese, Language.French);
		AddSupportedTranslation(Language.French, Language.Japanese);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://nihongobenkyo.org/"));
	}
}
public class DictdElementsDictionary : DictDMonolingualDictionary
{
	public DictdElementsDictionary()
	{
		Name = "elements";
		Description = "The Elements (22Oct97)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Chemistry);

		Urls.Add(new Uri("dict://dict.tugraz.at/"));
		Urls.Add(new Uri("dict://dict.tu-chemnitz.de/"));
		Urls.Add(new Uri("dict://la-sorciere.de/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdEngAraDictionary : DictDBilingualDictionary
{
	public DictdEngAraDictionary()
	{
		Name = "eng-ara";
		Description = "English-Arabic FreeDict Dictionary";
		AddSupportedTranslation(Language.English, Language.Arabic);
		AddSupportedTranslation(Language.English_GB, Language.Arabic);
		AddSupportedTranslation(Language.English_US, Language.Arabic);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdEngcomDictionary : DictDBilingualDictionary
{
	public DictdEngcomDictionary()
	{
		Name = "engcom";
		Description = "The Open English-Russian Computer Dictionary";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdEngCroDictionary : DictDBilingualDictionary
{
	public DictdEngCroDictionary()
	{
		Name = "eng-cro";
		Description = "English-Croatian Freedict Dictionary";
		AddSupportedTranslation(Language.English, Language.Croatian);
		AddSupportedTranslation(Language.English_GB, Language.Croatian);
		AddSupportedTranslation(Language.English_US, Language.Croatian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdEngCzeDictionary : DictDBilingualDictionary
{
	public DictdEngCzeDictionary()
	{
		Name = "eng-cze";
		Description = "English-Czech Freedict Dictionary";
		AddSupportedTranslation(Language.English, Language.Czech);
		AddSupportedTranslation(Language.English_GB, Language.Czech);
		AddSupportedTranslation(Language.English_US, Language.Czech);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdEngDeuDictionary : DictDBilingualDictionary
{
	public DictdEngDeuDictionary()
	{
		Name = "eng-deu";
		Description = "English-German Freedict dictionary";
		AddSupportedTranslation(Language.English, Language.German);
		AddSupportedTranslation(Language.English_GB, Language.German);
		AddSupportedTranslation(Language.English_US, Language.German);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://la-sorciere.de/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdEngHinDictionary : DictDBilingualDictionary
{
	public DictdEngHinDictionary()
	{
		Name = "eng-hin";
		Description = "English-Hindi Freedict Dictionary";
		AddSupportedTranslation(Language.English, Language.Hindi);
		AddSupportedTranslation(Language.English_GB, Language.Hindi);
		AddSupportedTranslation(Language.English_US, Language.Hindi);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdEngHunDictionary : DictDBilingualDictionary
{
	public DictdEngHunDictionary()
	{
		Name = "eng-hun";
		Description = "English-Hungarian Freedict Dictionary";
		AddSupportedTranslation(Language.English, Language.Hungarian);
		AddSupportedTranslation(Language.English_GB, Language.Hungarian);
		AddSupportedTranslation(Language.English_US, Language.Hungarian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdEngPorDictionary : DictDBilingualDictionary
{
	public DictdEngPorDictionary()
	{
		Name = "eng-por";
		Description = "English-Portugese Freedict dictionary";
		AddSupportedTranslation(Language.English, Language.Portuguese);
		AddSupportedTranslation(Language.English_GB, Language.Portuguese);
		AddSupportedTranslation(Language.English_US, Language.Portuguese);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdEngTurDictionary : DictDBilingualDictionary
{
	public DictdEngTurDictionary()
	{
		Name = "eng-tur";
		Description = "English-Turkish FreeDict Dictionary";
		AddSupportedTranslation(Language.English, Language.Turkish);
		AddSupportedTranslation(Language.English_GB, Language.Turkish);
		AddSupportedTranslation(Language.English_US, Language.Turkish);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdEstonian_etRuDictionary : DictDBilingualDictionary
{
	public DictdEstonian_etRuDictionary()
	{
		Name = "estonian_et-ru";
		Description = "Estonian-Russian dictionary";
		AddSupportedTranslation(Language.Estonian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdEthnographicDictionary : DictDMonolingualDictionary
{
	public DictdEthnographicDictionary()
	{
		Name = "ethnographic";
		Description = "Ethnographic dictionary";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.History);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdFindictDictionary : DictDMonolingualDictionary
{
	public DictdFindictDictionary()
	{
		Name = "findict";
		Description = "Dictionary of the financial terms";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Bank);
		AddSupportedSubject(SubjectConstants.Business);
		AddSupportedSubject(SubjectConstants.Economy);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdFoldocDictionary : DictDMonolingualDictionary
{
	public DictdFoldocDictionary()
	{
		Name = "foldoc";
		Description = "The Free On-line Dictionary of Computing (15Feb98)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dict.tugraz.at/"));
		Urls.Add(new Uri("dict://dict.tu-chemnitz.de/"));
		Urls.Add(new Uri("dict://la-sorciere.de/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdGazCountyDictionary : DictDMonolingualDictionary
{
	public DictdGazCountyDictionary()
	{
		Name = "gaz-county";
		Description = "U.S. Gazetteer Counties (2000)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Places);

		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdGazetteerDictionary : DictDMonolingualDictionary
{
	public DictdGazetteerDictionary()
	{
		Name = "gazetteer";
		Description = "U.S. Gazetteer (1990)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Places);

		Urls.Add(new Uri("dict://dict.tu-chemnitz.de/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdGazPlaceDictionary : DictDMonolingualDictionary
{
	public DictdGazPlaceDictionary()
	{
		Name = "gaz-place";
		Description = "U.S. Gazetteer Places (2000)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Places);

		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdGazZipDictionary : DictDMonolingualDictionary
{
	public DictdGazZipDictionary()
	{
		Name = "gaz-zip";
		Description = "U.S. Gazetteer Zip Code Tabulation Areas (2000)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Places);

		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdGcideDictionary : DictDMonolingualDictionary
{
	public DictdGcideDictionary()
	{
		Name = "gcide";
		Description = "The Collaborative International Dictionary of English v.0.48";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dict.tugraz.at/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdGeology_enRuDictionary : DictDBilingualDictionary
{
	public DictdGeology_enRuDictionary()
	{
		Name = "geology_en-ru";
		Description = "Geological English-Russian dictionary";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Geology);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdGeology_ruEnDictionary : DictDBilingualDictionary
{
	public DictdGeology_ruEnDictionary()
	{
		Name = "geology_ru-en";
		Description = "Geological Russian-English dictionary";
		AddSupportedTranslation(Language.Russian, Language.English);
		AddSupportedTranslation(Language.Russian, Language.English_GB);
		AddSupportedTranslation(Language.Russian, Language.English_US);

		AddSupportedSubject(SubjectConstants.Geology);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdHi127Dictionary : DictDMonolingualDictionary
{
	public DictdHi127Dictionary()
	{
		Name = "hi127";
		Description = "The dictionary-pointer on Old Russian art";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.History);
		AddSupportedSubject(SubjectConstants.Bible);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdHinEngDictionary : DictDBilingualDictionary
{
	public DictdHinEngDictionary()
	{
		Name = "hin-eng";
		Description = "English-Hindi Freedict Dictionary [reverse index]";
		AddSupportedTranslation(Language.Hindi, Language.English);
		AddSupportedTranslation(Language.Hindi, Language.English_GB);
		AddSupportedTranslation(Language.Hindi, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdHitchcockDictionary : DictDMonolingualDictionary
{
	public DictdHitchcockDictionary()
	{
		Name = "hitchcock";
		Description = "Hitchcock's Bible Names Dictionary (late 1800's)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Bible);

		Urls.Add(new Uri("dict://dict.tugraz.at/"));
		Urls.Add(new Uri("dict://dict.tu-chemnitz.de/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdHunEngDictionary : DictDBilingualDictionary
{
	public DictdHunEngDictionary()
	{
		Name = "hun-eng";
		Description = "Hungarian-English FreeDict Dictionary";
		AddSupportedTranslation(Language.Hungarian, Language.English);
		AddSupportedTranslation(Language.Hungarian, Language.English_GB);
		AddSupportedTranslation(Language.Hungarian, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdIdiomsDictionary : DictDBilingualDictionary
{
	public DictdIdiomsDictionary()
	{
		Name = "idioms";
		Description = "Russian-English dictionary of idioms";
		AddSupportedTranslation(Language.Russian, Language.English);
		AddSupportedTranslation(Language.Russian, Language.English_GB);
		AddSupportedTranslation(Language.Russian, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdJargonDictionary : DictDMonolingualDictionary
{
	public DictdJargonDictionary()
	{
		Name = "jargon";
		Description = "The on-line hacker Jargon File, version 4.3.1, 29 JUN 2001";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dict.tugraz.at/"));
		Urls.Add(new Uri("dict://dict.tu-chemnitz.de/"));
		Urls.Add(new Uri("dict://la-sorciere.de/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdJmdictDictionary : DictDBilingualDictionary
{
	public DictdJmdictDictionary()
	{
		Name = "jmdict";
		Description = "Japanese to English dictionary";
		AddSupportedTranslation(Language.English, Language.Japanese);
		AddSupportedTranslation(Language.English_GB, Language.Japanese);
		AddSupportedTranslation(Language.English_US, Language.Japanese);
		AddSupportedTranslation(Language.Japanese, Language.English);
		AddSupportedTranslation(Language.Japanese, Language.English_GB);
		AddSupportedTranslation(Language.Japanese, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://nihongobenkyo.org/"));
	}
}
public class DictdJmnedictDictionary : DictDMonolingualDictionary
{
	public DictdJmnedictDictionary()
	{
		Name = "jmnedict";
		Description = "Japanese proper names dictionary";
		AddSupportedTranslation(Language.Japanese, Language.Japanese);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://nihongobenkyo.org/"));
	}
}
public class DictdKanjidic2Dictionary : DictDBilingualDictionary
{
	public DictdKanjidic2Dictionary()
	{
		Name = "kanjidic2";
		Description = "Kanji dictionary";
		AddSupportedTranslation(Language.English, Language.Japanese);
		AddSupportedTranslation(Language.English_GB, Language.Japanese);
		AddSupportedTranslation(Language.English_US, Language.Japanese);
		AddSupportedTranslation(Language.Japanese, Language.English);
		AddSupportedTranslation(Language.Japanese, Language.English_GB);
		AddSupportedTranslation(Language.Japanese, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://nihongobenkyo.org/"));
	}
}
public class DictdKorolew_enRuDictionary : DictDBilingualDictionary
{
	public DictdKorolew_enRuDictionary()
	{
		Name = "korolew_en-ru";
		Description = "English-Russian dictionary - N.Korolew";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdKorolew_ruEnDictionary : DictDBilingualDictionary
{
	public DictdKorolew_ruEnDictionary()
	{
		Name = "korolew_ru-en";
		Description = "Russian-English dictionary - N.Korolew";
		AddSupportedTranslation(Language.Russian, Language.English);
		AddSupportedTranslation(Language.Russian, Language.English_GB);
		AddSupportedTranslation(Language.Russian, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdLatrusDictionary : DictDBilingualDictionary
{
	public DictdLatrusDictionary()
	{
		Name = "latrus";
		Description = "Latin-Russian Dictionary";
		AddSupportedTranslation(Language.Latin, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdMagusDictionary : DictDBilingualDictionary
{
	public DictdMagusDictionary()
	{
		Name = "magus";
		Description = "New large English-Russian dictionary";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdMech_nomimeDictionary : DictDBilingualDictionary
{
	public DictdMech_nomimeDictionary()
	{
		Name = "mech_nomime";
		Description = "English-Russian dictionary of science and mechanics";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
	}
}
public class DictdMeddictDictionary : DictDMonolingualDictionary
{
	public DictdMeddictDictionary()
	{
		Name = "meddict";
		Description = "Russian medical dictionary";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Medicine);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdMobyThesDictionary : DictDSynonymsDictionary
{
	public DictdMobyThesDictionary()
	{
		Name = "moby-thes";
		Description = "Moby Thesaurus II by Grady Ward, 1.0";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdMueller24Dictionary : DictDBilingualDictionary
{
	public DictdMueller24Dictionary()
	{
		Name = "mueller24";
		Description = "English-Russian Dictionary by Professor V.K.Mueller, 24-th Revised Edition";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdMuiswerkDictionary : DictDMonolingualDictionary
{
	public DictdMuiswerkDictionary()
	{
		Name = "muiswerk";
		Description = "Dutch monolingual dictionary, Copyright (C) 1995-1999 Muiswerk Educatief (www.muiswerk.nl)";
		AddSupportedTranslation(Language.Dutch, Language.Dutch);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdNldDeuDictionary : DictDBilingualDictionary
{
	public DictdNldDeuDictionary()
	{
		Name = "nld-deu";
		Description = "Nederlands-German Freedict dictionary";
		AddSupportedTranslation(Language.Dutch, Language.German);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdNldEngDictionary : DictDBilingualDictionary
{
	public DictdNldEngDictionary()
	{
		Name = "nld-eng";
		Description = "Nederlands-English Freedict dictionary";
		AddSupportedTranslation(Language.Dutch, Language.English);
		AddSupportedTranslation(Language.Dutch, Language.English_GB);
		AddSupportedTranslation(Language.Dutch, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdNldFraDictionary : DictDBilingualDictionary
{
	public DictdNldFraDictionary()
	{
		Name = "nld-fra";
		Description = "Nederlands-French Freedict dictionary";
		AddSupportedTranslation(Language.Dutch, Language.French);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdObiBioDictionary : DictDMonolingualDictionary
{
	public DictdObiBioDictionary()
	{
		Name = "obi-bio";
		Description = "Biographic reference book";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.History);

		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdOzhegovDictionary : DictDMonolingualDictionary
{
	public DictdOzhegovDictionary()
	{
		Name = "ozhegov";
		Description = "Explanatory dictionary of Russian language by Ozhegov";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdOzhshvDictionary : DictDMonolingualDictionary
{
	public DictdOzhshvDictionary()
	{
		Name = "ozhshv";
		Description = "Explanatory Dictionary of Russian language by Ozhegov and Shvedova";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdPorEngDictionary : DictDBilingualDictionary
{
	public DictdPorEngDictionary()
	{
		Name = "por-eng";
		Description = "Portugese-English Freedict dictionary";
		AddSupportedTranslation(Language.Portuguese, Language.English);
		AddSupportedTranslation(Language.Portuguese, Language.English_GB);
		AddSupportedTranslation(Language.Portuguese, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdReligionDictionary : DictDMonolingualDictionary
{
	public DictdReligionDictionary()
	{
		Name = "religion";
		Description = "History of religion";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.History);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdScAbbrDictionary : DictDMonolingualDictionary
{
	public DictdScAbbrDictionary()
	{
		Name = "sc-abbr";
		Description = "English-Russian Computer Science Abbreviations";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdSdict_fiRuDictionary : DictDBilingualDictionary
{
	public DictdSdict_fiRuDictionary()
	{
		Name = "sdict_fi-ru";
		Description = "Finnish-Russian dictionary";
		AddSupportedTranslation(Language.Finnish, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdSdict_ruEnDictionary : DictDBilingualDictionary
{
	public DictdSdict_ruEnDictionary()
	{
		Name = "sdict_ru-en";
		Description = "Russian-English full dictionary";
		AddSupportedTranslation(Language.Russian, Language.Finnish);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdSesDictionary : DictDMonolingualDictionary
{
	public DictdSesDictionary()
	{
		Name = "ses";
		Description = "The modern encyclopaedic dictionary (Russian)";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdShakespeareDictionary : DictDMonolingualDictionary
{
	public DictdShakespeareDictionary()
	{
		Name = "Shakespeare";
		Description = "Shakespearean Words and Meanings";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.History);

		Urls.Add(new Uri("dict://linicks.net/"));
	}
}
public class DictdSinyagin_alexeymavrinDictionary : DictDBilingualDictionary
{
	public DictdSinyagin_alexeymavrinDictionary()
	{
		Name = "sinyagin_alexeymavrin";
		Description = "English-Russian dictionary by Sinyagin/Alexey Mavrin";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdSinyagin_businessDictionary : DictDBilingualDictionary
{
	public DictdSinyagin_businessDictionary()
	{
		Name = "sinyagin_business";
		Description = "English-Russian dictionary of business by Sinyagin";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Business);
		AddSupportedSubject(SubjectConstants.Bank);
		AddSupportedSubject(SubjectConstants.Economy);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdSinyagin_computerDictionary : DictDBilingualDictionary
{
	public DictdSinyagin_computerDictionary()
	{
		Name = "sinyagin_computer";
		Description = "English-Russian dictionary of computer science by Sinyagin";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdSinyagin_general_erDictionary : DictDBilingualDictionary
{
	public DictdSinyagin_general_erDictionary()
	{
		Name = "sinyagin_general_er";
		Description = "English-Russian dictionary by Sinyagin";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdSinyagin_general_reDictionary : DictDBilingualDictionary
{
	public DictdSinyagin_general_reDictionary()
	{
		Name = "sinyagin_general_re";
		Description = "Russian-English dictionary by Sinyagin";
		AddSupportedTranslation(Language.Russian, Language.English);
		AddSupportedTranslation(Language.Russian, Language.English_GB);
		AddSupportedTranslation(Language.Russian, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdSmileyDictionary : DictDMonolingualDictionary
{
	public DictdSmileyDictionary()
	{
		Name = "smiley";
		Description = "Dictionary of smileys";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdSNCTDictionary : DictDMonolingualDictionary
{
	public DictdSNCTDictionary()
	{
		Name = "SN-CT";
		Description = "Computer Terms Glossary, 2008-08-25 (Copyright 1998-2008 Saugus.net)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dict.saugus.net/"));
	}
}
public class DictdSNFEDictionary : DictDMonolingualDictionary
{
	public DictdSNFEDictionary()
	{
		Name = "SN-FE";
		Description = "Filename Extensions List, 2008-08-25 (Copyright 1998-2008 Saugus.net)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dict.saugus.net/"));
	}
}
public class DictdSNFSDictionary : DictDMonolingualDictionary
{
	public DictdSNFSDictionary()
	{
		Name = "SN-FS";
		Description = "Guide to Free Software, 2008-08-25 (Copyright 1998-2008 Saugus.net)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dict.saugus.net/"));
	}
}
public class DictdSokrat_enRuDictionary : DictDBilingualDictionary
{
	public DictdSokrat_enRuDictionary()
	{
		Name = "sokrat_en-ru";
		Description = "English-Russian dictionary (Sokrat)";
		AddSupportedTranslation(Language.English, Language.Russian);
		AddSupportedTranslation(Language.English_GB, Language.Russian);
		AddSupportedTranslation(Language.English_US, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdSokrat_ruEnDictionary : DictDBilingualDictionary
{
	public DictdSokrat_ruEnDictionary()
	{
		Name = "sokrat_ru-en";
		Description = "Russian-English dictionary (Sokrat)";
		AddSupportedTranslation(Language.Russian, Language.English);
		AddSupportedTranslation(Language.Russian, Language.English_GB);
		AddSupportedTranslation(Language.Russian, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdStardicDictionary : DictDBilingualDictionary
{
	public DictdStardicDictionary()
	{
		Name = "stardic";
		Description = "Stardic English-Chinese Dictionary";
		AddSupportedTranslation(Language.English, Language.Chinese);
		AddSupportedTranslation(Language.English_GB, Language.Chinese);
		AddSupportedTranslation(Language.English_US, Language.Chinese);
		AddSupportedTranslation(Language.English, Language.Chinese_CN);
		AddSupportedTranslation(Language.English_GB, Language.Chinese_CN);
		AddSupportedTranslation(Language.English_US, Language.Chinese_CN);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
	}
}
public class DictdSwedish_ruSvDictionary : DictDBilingualDictionary
{
	public DictdSwedish_ruSvDictionary()
	{
		Name = "swedish_ru-sv";
		Description = "Russian-Swedish dictionary";
		AddSupportedTranslation(Language.Russian, Language.Swedish);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdSwedish_svRuDictionary : DictDBilingualDictionary
{
	public DictdSwedish_svRuDictionary()
	{
		Name = "swedish_sv-ru";
		Description = "Swedish-Russian dictionary";
		AddSupportedTranslation(Language.Swedish, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdTanaka_corpusDictionary : DictDBilingualDictionary
{
	public DictdTanaka_corpusDictionary()
	{
		Name = "tanaka_corpus";
		Description = "Japanese-English sentence examples";
		AddSupportedTranslation(Language.Japanese, Language.English);
		AddSupportedTranslation(Language.Japanese, Language.English_GB);
		AddSupportedTranslation(Language.Japanese, Language.English_US);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://nihongobenkyo.org/"));
	}
}
public class DictdTeoDictionary : DictDMonolingualDictionary
{
	public DictdTeoDictionary()
	{
		Name = "teo";
		Description = "Theosophic dictionary (Russian)";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.History);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdUshakovDictionary : DictDMonolingualDictionary
{
	public DictdUshakovDictionary()
	{
		Name = "ushakov";
		Description = "Explanatory Dictionary of Ushakov";
		AddSupportedTranslation(Language.Russian, Language.Russian);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictd.xdsl.by/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
	}
}
public class DictdVeraDictionary : DictDMonolingualDictionary
{
	public DictdVeraDictionary()
	{
		Name = "vera";
		Description = "V.E.R.A. -- Virtual Entity of Relevant Acronyms (December 2003)";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Informatics);
		AddSupportedSubject(SubjectConstants.Internet);

		Urls.Add(new Uri("dict://dict.tugraz.at/"));
		Urls.Add(new Uri("dict://la-sorciere.de/"));
		Urls.Add(new Uri("dict://dict.bober757.org.ru/"));
		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
		Urls.Add(new Uri("dict://dict.dvo.ru/"));
	}
}
public class DictdWorld02Dictionary : DictDMonolingualDictionary
{
	public DictdWorld02Dictionary()
	{
		Name = "world02";
		Description = "CIA World Factbook 2002";
		AddSupportedTranslation(Language.English, Language.English);
		AddSupportedTranslation(Language.English_GB, Language.English_GB);
		AddSupportedTranslation(Language.English_US, Language.English_US);

		AddSupportedSubject(SubjectConstants.Economy);
		AddSupportedSubject(SubjectConstants.Places);

		Urls.Add(new Uri("dict://alt0.dict.org/"));
		Urls.Add(new Uri("dict://dict1.us.dict.org/"));
		Urls.Add(new Uri("dict://dict.org/"));
	}
}
public class DictdXdictDictionary : DictDBilingualDictionary
{
	public DictdXdictDictionary()
	{
		Name = "xdict";
		Description = "XDICT the English-Chinese dictionary";
		AddSupportedTranslation(Language.English, Language.Chinese);
		AddSupportedTranslation(Language.English_GB, Language.Chinese);
		AddSupportedTranslation(Language.English_US, Language.Chinese);
		AddSupportedTranslation(Language.English, Language.Chinese_CN);
		AddSupportedTranslation(Language.English_GB, Language.Chinese_CN);
		AddSupportedTranslation(Language.English_US, Language.Chinese_CN);

		AddSupportedSubject(SubjectConstants.Common);

		Urls.Add(new Uri("dict://dictionary.bishopston.net/"));
	}
}




}
